[main]
serial_baud = 9600
serial_parity = N
serial_data_bit = 8
serial_stop_bit = 1
serial_device = /dev/ttyS1
logfile = /var/log/shs.log

[card]
id = 0
address = 1
inputs = 8
outputs = 8
disabled = false
input_types = [eltako,finder,finder,finder,finder,finder,finder,finder]
input_broken = [false,false,false,false,false,false,false,false]
output_broken = [false,false,false,false,false,false,false,false]

[card]
id = 1
address = 2
inputs = 8
outputs = 8
disabled = false
input_types = [eltako,finder,finder,finder,finder,finder,finder,finder]
input_broken = [false,false,false,false,false,false,false,false]
output_broken = [false,false,false,false,false,false,false,false]

[card]
id = 2
address = 3
inputs = 8
outputs = 8
disabled = false
input_types = [eltako,finder,finder,finder,finder,finder,finder,finder]
input_broken = [false,false,false,false,false,false,false,false]
output_broken = [false,false,false,false,false,false,false,false]

[card]
id = 3
address = 4
inputs = 8
outputs = 8
disabled = false
input_types = [eltako,finder,finder,finder,finder,finder,finder,finder]
input_broken = [false,false,false,false,false,false,false,false]
output_broken = [false,false,false,false,false,false,false,false]

[sensor]
id = 240
name = kueche
address = 11
disabled = false
help = "Aktuelle Temperatur"
type = "gauge"
metric = kueche_temperatur_celsius
help = "Aktuelle Luftfeuchtigkeit"
type = "gauge"
metric = kueche_luftfeuchtigkeit_prozent
